#!/usr/bin/env node
/**
 * setup.js
 *
 * One-time setup helper. Reads .env and:
 *   1. Patches wrangler.toml with real IDs (account_id, database_id, kv id)
 *   2. Generates .dev.vars for `wrangler dev` local secrets
 *   3. Pushes Cloudflare secrets (TG_BOT_TOKEN, TG_CHAT_ID, etc.) via wrangler CLI
 *
 * Usage:
 *   node setup.js           — patch wrangler.toml + generate .dev.vars
 *   node setup.js --secrets — also push secrets to Cloudflare (requires wrangler login)
 *   node setup.js --all     — do everything
 */

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ─── Load .env ───────────────────────────────────────────────────────────────
function loadEnv(filePath = '.env') {
  if (!fs.existsSync(filePath)) {
    console.error(`❌  ${filePath} not found. Copy .env.example → .env and fill it in.`);
    process.exit(1);
  }

  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  const env   = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const [key, ...rest] = trimmed.split('=');
    env[key.trim()] = rest.join('=').trim();
  }

  return env;
}

// ─── Patch wrangler.toml ─────────────────────────────────────────────────────
function patchWranglerToml(env) {
  const tomlPath = 'wrangler.toml';
  if (!fs.existsSync(tomlPath)) {
    console.error('❌  wrangler.toml not found');
    process.exit(1);
  }

  let toml = fs.readFileSync(tomlPath, 'utf8');
  let changed = false;

  const replacements = {
    YOUR_ACCOUNT_ID:            env.CF_ACCOUNT_ID,
    YOUR_D1_DATABASE_ID:        env.CF_D1_DATABASE_ID,
    YOUR_KV_NAMESPACE_ID:       env.CF_KV_NAMESPACE_ID,
    YOUR_KV_PREVIEW_NAMESPACE_ID: env.CF_KV_PREVIEW_NAMESPACE_ID,
  };

  for (const [placeholder, value] of Object.entries(replacements)) {
    if (!value) {
      console.warn(`⚠️   ${placeholder} not set in .env — skipping`);
      continue;
    }
    if (toml.includes(placeholder)) {
      // Replace all occurrences
      toml = toml.split(placeholder).join(value);
      console.log(`✅  Replaced ${placeholder} → ${value}`);
      changed = true;
    }
  }

  if (changed) {
    fs.writeFileSync(tomlPath, toml, 'utf8');
    console.log('📝  wrangler.toml updated\n');
  } else {
    console.log('ℹ️   wrangler.toml already up to date\n');
  }
}

// ─── Generate .dev.vars ──────────────────────────────────────────────────────
// wrangler dev reads .dev.vars as local secrets (gitignored)
function generateDevVars(env) {
  const secretKeys = ['TG_BOT_TOKEN', 'TG_CHAT_ID', 'WORKER_API_URL'];
  const lines = [
    '# Auto-generated by setup.js — do not commit',
    '# Used by `wrangler dev` for local secret injection',
    '',
  ];

  for (const key of secretKeys) {
    if (env[key]) {
      lines.push(`${key}=${env[key]}`);
    }
  }

  fs.writeFileSync('.dev.vars', lines.join('\n') + '\n', 'utf8');
  console.log('✅  .dev.vars generated (for wrangler dev)\n');
}

// ─── Push Cloudflare secrets ─────────────────────────────────────────────────
function pushSecrets(env) {
  const secretKeys = ['TG_BOT_TOKEN', 'TG_CHAT_ID', 'WORKER_API_URL'];

  console.log('🔐  Pushing secrets to Cloudflare...\n');

  for (const key of secretKeys) {
    const value = env[key];
    if (!value) {
      console.warn(`⚠️   ${key} not set in .env — skipping`);
      continue;
    }

    try {
      // Echo value into wrangler secret put (non-interactive)
      execSync(`echo "${value}" | wrangler secret put ${key}`, {
        stdio: ['pipe', 'inherit', 'inherit'],
        shell: true,
      });
      console.log(`✅  Secret pushed: ${key}`);
    } catch (err) {
      console.error(`❌  Failed to push ${key}:`, err.message);
    }
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────
(function main() {
  const args    = process.argv.slice(2);
  const doSecrets = args.includes('--secrets') || args.includes('--all');

  console.log('🚀  AI Chatbot Setup\n');

  const env = loadEnv('.env');

  patchWranglerToml(env);
  generateDevVars(env);

  if (doSecrets) {
    pushSecrets(env);
  } else {
    console.log('💡  To push secrets to Cloudflare, run: node setup.js --secrets\n');
    console.log('    Or set them manually:');
    console.log('      wrangler secret put TG_BOT_TOKEN');
    console.log('      wrangler secret put TG_CHAT_ID');
    console.log('      wrangler secret put WORKER_API_URL  (optional)\n');
  }

  console.log('✅  Setup complete. Next steps:');
  console.log('    1. wrangler d1 execute support-db --file=schema.sql');
  console.log('    2. wrangler deploy');
  console.log('    3. node upload-knowledge.js --samples\n');
})();
